### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by ghost** [nnarhinen/react-pdf#12]
Any way to get hyperlinks working for this?

**Comment by devang-kredx** [comment]
@Thomsos Were you able to figure this out?

**Comment by ghost** [comment]
@devang-kredx I just ended up using the official pdf.js http://mozilla.github.io/pdf.js/

**Comment by wojtekmaj** [comment]
Hi @Thomsos - pdf.js library we're using is just for rendering PDFs. Of course, on top of that we could build fully-featured PDF viewer, but I don't think that could happen anytime soon, as Mozilla's viewer is unmatchable. We could end up with PDF.js wrapper for React, though :) I'll inform you if I come up with this, although that would be an entirely different repo.
