### ISSUE TITLE
Plans to integrate text layers?

### ISSUE THREAD

**Issue by dijs** [nnarhinen/react-pdf#17]

**Comment by wojtekmaj** [comment]
@dijs Could you elaborate on that? I'm not quite sure what do you mean by text layers.

**Comment by dijs** [comment]
Oooo... This was a while ago. If I remember correctly, I was trying to know text characters and positions.

**Comment by wojtekmaj** [comment]
Hmmmm... It's very easily available via page.getTextContent in pdf.js, the result is like so:

![image](https://cloud.githubusercontent.com/assets/5426427/22626761/5ebd7b7a-ebb5-11e6-853e-16e5e3d0a931.png)

If there's still some demand, I could implement a way to get current document & page from react-pdf component which would make it possible to call page.getTextContent on it.

**Comment by wojtekmaj** [comment]
@dijs Sneak peek! :D 2.0.0-alpha.2

![image](https://user-images.githubusercontent.com/5426427/28251552-294cda7c-6a80-11e7-9c49-e3545969f482.png)
