### ISSUE TITLE
allow to style canvas and set fixed width 

### ISSUE THREAD

**Issue by macrozone** [nnarhinen/react-pdf#20]
currently, it seems not possible to scale the canvas properly. The scale-property sets the render-scale but this is blurry on newer displays.

The solution would be to set the width of the canvas with css, but this is currently not possible with inline styles.

**Comment by AlexFloor95** [comment]
Looking for this feature aswell is there a proper workaround?

**Comment by wojtekmaj** [comment]
@AlexFloor95 @macrozone Maybe you guys would be interested with my fork then? It fully supports Hi-DPI screens out of the box, and you can also specify a desired width on top of that. I just published this update so I can't wait for your comments! Check it out! https://github.com/wojtekmaj/react-pdf/

**Comment by nnarhinen** [comment]
@wojtekmaj I gave you push rights to this repository. If you tell me your NPM user name I will give you push rights there too.

**Comment by wojtekmaj** [comment]
@nnarhinen Thank you! My npm username is wojtekmaj as well.

**Comment by wojtekmaj** [comment]
Fixed in #34.

**Comment by nnarhinen** [comment]
You should be able to publish to NPM now
