### ISSUE TITLE
Patch for fixing .getDOMNode() access warning

### ISSUE THREAD

**Issue by tomkomt** [nnarhinen/react-pdf#22]
Hello,

everytime I open pdf through `react-pdf`, I got `Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by React-PDF.`

This is easily fixable. In `index.js` replace this line:
`var canvas = self.refs.pdfCanvas.getDOMNode(),` on line 65 with this line:
`var canvas = ReactDOM.findDOMNode(self.refs.pdfCanvas),`

And of course import `react-dom` as ReactDOM

**Comment by nnarhinen** [comment]
Pull request please :)

**Comment by tomkomt** [comment]
There is no need for that. I noticed later that you already have implemented what I proposed in 0.0.10. Our package.json got stuck with 0.0.9.
