### ISSUE TITLE
Does it have PDF toolbar?

### ISSUE THREAD

**Issue by BesatZardosht** [nnarhinen/react-pdf#23]
I installed this module but it is only showing one page of the PDF.
and the there is no toolbar on top of the pdf and scrolling does not work.

any help is appreciated

**Comment by nnarhinen** [comment]
No, there is no toolbar, that is left for the implementor. You can change page by passing it via props. You can check the example implementation from the `example` directory.

**Comment by dziamid** [comment]
Any suggestions on the toolbar implementations?

**Comment by wojtekmaj** [comment]
@dziamid, check sample/test pages that are included in react-pdf as of 1.6.0 :)
