### ISSUE TITLE
SyntaxError: Parse error - Wkhtmltopdf with react-pdf lib

### ISSUE THREAD

**Issue by marlon407** [nnarhinen/react-pdf#25]
Hi all, 
I am using wkhtmltopdf version 0.12.2.1 (with patched qt) to render my reactJs app! It worked fine, until I added the react-pdf lib to render the pdf generated inside my app. I followed the code described on react-pdf documentation (see https://www.npmjs.com/package/react-pdf) to make it work.

The pdf is rendered inside my page, and it looks pretty cool. But when I try to run wkhtmltopdf again, to generate a pdf of any page of my app, the following error is returned:

```
desenv01@desenv01-PC:~$ wkhtmltopdf -O Landscape --print-media-type --debug-javascript  http://localhost:3000/report/1 report.pdfLoading pages (1/6)
Warning: undefined:0 ReferenceError: Can't find variable: Float64Array
Warning: http://localhost:3000/assets/js/app.js:46789 SyntaxError: Parse error
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done
```

Then, I went to my app.js to see what's on line 46789:

```
set href(href) {
  clear.call(this);
  parse.call(this, href);
},

get protocol() {
  return this._scheme + ':';
},
set protocol(protocol) {
  if (this._isInvalid)
    return;
  parse.call(this, protocol + ':', 'scheme start');
},
```

The error happens on the line that says `parse.call(this, href);` which is part of `pdf.combined.js` script.

I could not find any solution online so I wondered if there is anyone who might know if I did something wrong or a way to work around it.

Thanks..

**Comment by wojtekmaj** [comment]
Hi @marlon407. This is a PDF.js issue and you should probably report it to Mozilla instead. But would you kindly check is that's an issue on react-pdf 1.6.0?

**Comment by wojtekmaj** [comment]
Closed because of no interest. Happy to reopen if the discussion continues.
