### ISSUE TITLE
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

### ISSUE THREAD

**Issue by oscaroceguera** [nnarhinen/react-pdf#27]

**Comment by natcohen** [comment]
I'm also getting this warning with chrome 53. Here is a [working example](http://plnkr.co/edit/fCfgAxR8408zXT0vSb3e?p=preview) (check the console when you upload a pdf)

**Comment by nnarhinen** [comment]
This is something that has to be fixed in pdf.js - https://github.com/mozilla/pdf.js/issues/6306
