### ISSUE TITLE
Annotator.js with react

### ISSUE THREAD

**Issue by 0b01** [nnarhinen/react-pdf#28]
I'm new to React.js. How hard would it be to integrate annotatorjs with react-pdf?

**Comment by mvanlonden** [comment]
checkout https://github.com/mzabriskie/pdf-annotate.js it does a great job of putting an annotation layer on PDFjs

**Comment by wojtekmaj** [comment]
Hey @rickyhan, not sure if you're still interested but if you are, check out the new React-PDF version that sits on wojtekmaj/react-pdf. It supports annotations out of the box!

**Comment by nikolayg** [comment]
@wojtekmaj I couldn't see any documentation or examples on how to annotate or highlight with React-PDF. Could you please point me to something to get me started?
