### ISSUE TITLE
PDF file is displayed upside down at first, it rotates once I changed to another page

### ISSUE THREAD

**Issue by figalex** [nnarhinen/react-pdf#31]
The first time the pdf file is loaded it is shown upside down, once I called a function to move to next page it displays correctly. What could I be doing wrong?

**Comment by wojtekmaj** [comment]
Could you provide more info? A PDF on which it happens and environment info?

**Comment by wojtekmaj** [comment]
Okay, I was able to reproduce this and I'm quire confident that should be reported in to [Mozilla](https://github.com/mozilla/pdf.js).

**Comment by wojtekmaj** [comment]
Hi @figalex, I believe I've fixed this error on my fork of this repo. If you're still interested, have a look!

**Comment by wojtekmaj** [comment]
Fixed in #34.
