### ISSUE TITLE
ES5

### ISSUE THREAD

**Issue by rbembleton** [nnarhinen/react-pdf#36]
Hey!

Was having a problem with this code, because my current code base uses some ES5. Your ES5 folder contains some ES6 code.

```
// import React, { Component, PropTypes } from 'react' ; // old code
var React = require('react');
var Component = React.Component;
var PropTypes = React.PropTypes;

// ...

// export default ReactPDF; // old code
module.exports = ReactPDF;
```

By fixing these couple lines, the code worked for me.

**Comment by wojtekmaj** [comment]
Hmmm... I guess our babelrc config is not transpiling enough! I'll have a look into this as soon as I can.

**Comment by wojtekmaj** [comment]
@rbembleton, would you kindly temporary edit your package.json to read as follows:

`"react-pdf": "git://github.com/wojtekmaj/react-pdf.git#bugfix/commonjs-in-es5"`

and confirm whether that fixes the problem?

**Comment by rbembleton** [comment]
Yup! That seemed to work 💃

**Comment by wojtekmaj** [comment]
@rbembleton 1.6.1 that includes this fix is out now :)
