### ISSUE TITLE
Demo is minified

### ISSUE THREAD

**Issue by alondahari** [nnarhinen/react-pdf#46]
Hi,
The code in sample/index.js is minified, so not that helpful...

**Comment by wojtekmaj** [comment]
Hello,
indeed it is minified, as ./sample and ./test folders are created by Webpack, as configured in ./webpack.config.sample.js and ./webpack.config.test.js respectively.

You'd want to visit [./src-sample](https://github.com/nnarhinen/react-pdf/tree/master/src-sample) folder to see the code before Webpack got to work :)

**Comment by alondahari** [comment]
Haha right in front of me... :)
