### ISSUE TITLE
use npm version of pdfjs

### ISSUE THREAD

**Issue by luisrudge** [nnarhinen/react-pdf#7]
this is the official npm package: https://www.npmjs.com/package/pdfjs-dist

**Comment by nnarhinen** [comment]
AFAIK that distributed package still doesn't offer any commonJS module definitions and thus does not help us at all.

**Comment by JMStudiosJoe** [comment]
So does this npm package work?

**Comment by nnarhinen** [comment]
@JMStudiosJoe yes, but as https://github.com/nnarhinen/react-pdf#pitfalls states, this library assumes a global `PDFJS` variable to be found.

**Comment by mattikl** [comment]
`react-pdf` worked out of the box after installing `pdfjs-dist` and then

``` js
require('pdfjs-dist/build/pdf.combined')
```

After that the global `PDFJS` variable exists, so I think `react-pdf` could depend on `pdfjs-dist` and include the `require`. At least it would be good to document this way of using the library.

**Comment by faisalarbain** [comment]
@mattikl nice. works for me. thanks

**Comment by Nopzen** [comment]
Thanks @mattikl. Made it work for me aswell!

**Comment by klacointe** [comment]
:+1:

**Comment by innerexception** [comment]
Be aware pdf.combined.js disables web worker functionality and causes severe performance issues in some cases
