### ISSUE TITLE
Are re-renders "efficient"?

### ISSUE THREAD

**Issue by adelevie** [nnarhinen/react-pdf#9]
Let's say I have a 5 page PDF. Then the PDF is updated and I pass in a new file to the `<PDF>` component. Will all 5 pages re-render, or will only the right part of the canvas re-render? In other words, are the canvas changes diffed the updated efficiently the same way HTML is updated in React?

**Comment by JMStudiosJoe** [comment]
+1

**Comment by erikras** [comment]
No, since the rendering to the canvas is done by PDF.js which is not done via React.

But your options are to rewrite a PDF renderer in React or use this bridge. :confused:

**Comment by adelevie** [comment]
One strategy could be to programmatically predict which pages will change
and only re-render those. For PDF forms, this should be pretty easy.
